In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
df_train = pd.read_csv('../Data/train.csv')
df_metadata = pd.read_csv('../Data/metaData.csv')
df_train.sample(5)

,event_id,num_perimeters_0_5h,dt_first_last_0_5h,low_temporal_resolution_0_5h,area_first_ha,area_growth_abs_0_5h,area_growth_rel_0_5h,area_growth_rate_ha_per_h,log1p_area_first,log1p_growth,...,dist_fit_r2_0_5h,alignment_cos,alignment_abs,cross_track_component,along_track_speed,event_start_hour,event_start_dayofweek,event_start_month,time_to_hit_hours,event
139,65120642,4,4.640813,0,420.398730,352.032424,0.837377,75.855761,6.043579,5.86656,...,0.658097,0.796469,0.796469,71.511,94.192518,17,2,6,2.483279,0
74,39687487,2,1.424188,0,2.011464,0.000000,0.000000,0.000000,1.102426,0.00000,...,0.000000,0.488864,0.488864,0.000,0.000000,19,0,9,0.743442,1
176,80087496,1,0.000000,1,258.150907,0.000000,0.000000,0.000000,5.557411,0.00000,...,0.000000,0.000000,0.000000,0.000,0.000000,21,5,8,66.790141,0
142,66678641,1,0.000000,1,123.421747,0.000000,0.000000,0.000000,4.823677,0.00000,...,0.000000,0.000000,0.000000,0.000,0.000000,5,1,8,7.488617,1
162,73362817,1,0.000000,1,67.560539,0.000000,0.000000,0.000000,4.227717,0.00000,...,0.000000,0.000000,0.000000,0.000,0.000000,19,1,7,19.561849,1

In [8]:
df_metadata.head(39)

,column,type,category,description,units,range
0,event_id,identifier,identifier,Anonymized fire event identifier (stable rando...,NaN,NaN
1,time_to_hit_hours,target,target,Time from t0+5h until fire comes within 5km of...,hours,"[0, 72]"
2,event,target,target,"Event indicator: 1 if fire hit within 72h, 0 i...",NaN,NaN
3,num_perimeters_0_5h,feature,temporal_coverage,Number of perimeters within first 5 hours,NaN,NaN
4,dt_first_last_0_5h,feature,temporal_coverage,Time span between first and last perimeter (ho...,NaN,NaN
5,low_temporal_resolution_0_5h,feature,temporal_coverage,"Flag: 1 if dt < 0.5h or only 1 perimeter, else 0",NaN,NaN
6,area_first_ha,feature,growth,Initial fire area at t0 (hectares),NaN,NaN
7,area_growth_abs_0_5h,feature,growth,Feature from growth category,NaN,NaN
8,area_growth_rel_0_5h,feature,growth,Feature from growth category,NaN,NaN
9,area_growth_rate_ha_per_h,feature,growth,Area growth rate (hectares per hour),NaN,NaN
10,log1p_area_first,feature,growth,Feature from growth category,NaN,NaN
11,log1p_growth,feature,growth,Feature from growth category,NaN,NaN
12,log_area_ratio_0_5h,feature,growth,Feature from growth category,NaN,NaN
13,relative_growth_0_5h,feature,growth,Feature from growth category,NaN,NaN
14,radial_growth_m,feature,growth,Feature from growth category,NaN,NaN
15,radial_growth_rate_m_per_h,feature,growth,Feature from growth category,NaN,NaN
16,centroid_displacement_m,feature,centroid_kinematics,Feature from centroid_kinematics category,NaN,NaN
17,centroid_speed_m_per_h,feature,centroid_kinematics,Feature from centroid_kinematics category,NaN,NaN
18,spread_bearing_deg,feature,centroid_kinematics,Feature from centroid_kinematics category,NaN,NaN
19,spread_bearing_sin,feature,centroid_kinematics,Feature from centroid_kinematics category,NaN,NaN
20,spread_bearing_cos,feature,centroid_kinematics,Feature from centroid_kinematics category,NaN,NaN
21,dist_min_ci_0_5h,feature,distance,Minimum distance to nearest evac zone centroid...,NaN,NaN
22,dist_std_ci_0_5h,feature,distance,Feature from distance category,NaN,NaN
23,dist_change_ci_0_5h,feature,distance,Feature from distance category,NaN,NaN
24,dist_slope_ci_0_5h,feature,distance,Feature from distance category,NaN,NaN
25,closing_speed_m_per_h,feature,distance,Speed at which fire is closing distance to eva...,NaN,NaN
26,closing_speed_abs_m_per_h,feature,distance,Feature from distance category,NaN,NaN
27,projected_advance_m,feature,distance,Feature from distance category,NaN,NaN
28,dist_accel_m_per_h2,feature,distance,Feature from distance category,NaN,NaN
29,dist_fit_r2_0_5h,feature,distance,Feature from distance category,NaN,NaN
30,alignment_cos,feature,directionality,Feature from directionality category,NaN,NaN
31,alignment_abs,feature,directionality,Absolute alignment between fire motion and eva...,NaN,NaN
32,cross_track_component,feature,directionality,Feature from directionality category,NaN,NaN
33,along_track_speed,feature,directionality,Feature from directionality category,NaN,NaN
34,event_start_hour,feature,temporal_metadata,Hour of day when fire started (0-23),NaN,NaN
35,event_start_dayofweek,feature,temporal_metadata,"Day of week (0=Monday, 6=Sunday)",NaN,NaN
36,event_start_month,feature,temporal_metadata,Month when fire started (1-12),NaN,NaN

In [12]:
df_train.columns
df_train[[df_train.columns[1]]].value_counts()

num_perimeters_0_5h
1                      160
2                       25
3                        7
7                        7
4                        5
5                        5
12                       5
6                        2
9                        2
11                       1
13                       1
17                       1
Name: count, dtype: int64